name: Bug report
description: Report a bug with the AI SDK.
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        This template is to report bugs. If you need help with your own project, feel free to [start a new thread in our discussions](https://github.com/vercel/ai/discussions).
  - type: textarea
    attributes:
      label: Description
      description: A detailed description of the issue that you are encountering with the AI SDK, and how other people can reproduce it. This includes helpful information such as the API you are using, the framework and AI provider.
      placeholder: |
        Reproduction steps...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Code example
      description: Provide an example code snippet that has the problem.
      placeholder: |
        import { openai } from '@ai-sdk/openai';
        import { streamText } from 'ai';
        ...
  - type: input
    id: provider
    attributes:
      label: AI provider
      description: The AI provider (e.g. `@ai-sdk/openai`) that you are using, and its version (e.g. `1.0.0`).
      placeholder: |
        @ai-sdk/openai v1.0.0
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
